<a href="https://colab.research.google.com/github/sasichintada/ml-workshop/blob/main/numassig1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Perform arithmetic operations on NumPy arrays

In [ ]:
import numpy as np


##Arithmatic operations

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
add=a+b
sub=a-b
mul=a*b
div=a/b
mod=a%b
pow=a**2
floor=a//b
print("add=",add)
print("sub=",sub)
print("mul=",mul)
print("div=",div)
print("mod=",mod)
print("pow=",pow)
print("floor=",floor)

add= [5 7 9]
sub= [-3 -3 -3]
mul= [ 4 10 18]
div= [0.25 0.4  0.5 ]
mod= [1 2 3]
pow= [1 4 9]
floor= [0 0 0]


2.Write a script to compute the mean and standard deviation of a NumPy array

##mean and standard deviation


In [ ]:
a=np.array([2,4,6,8])
mean=np.mean(a)
standard=np.std(a)
print("mean deviation=",mean)
print("standard deviation=",standard)


mean deviation= 5.0
standard deviation= 2.23606797749979


3.Create a NumPy array of integers from 10 to 50 with a step size of 5


##using slicing

In [ ]:
a=np.arange(10,51,5)
print(a)

[10 15 20 25 30 35 40 45 50]


4.Reshape the array into a 2x4 matrix

##reshape

In [ ]:
a=np.arange(10,49,5)
reshape=a.reshape(2,4)
print(reshape)

[[10 15 20 25]
 [30 35 40 45]]


5.Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) .Extract the sub-matrix containing the last two rows and first two columns.


##sub-matrix

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
submatrix=arr[1:,:2]
print(submatrix)

[[4 5]
 [7 8]]


5.2Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) Replace all elements greater than 4 with 0.

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[arr>4]=0
print(arr)

[[1 2 3]
 [4 0 0]
 [0 0 0]]


6. Create two 1D arrays: a = np.array([1, 2, 3]),b = np.array([4, 5, 6]) Perform element-wise addition, multiplication, and division.


##creating two 1D arrays

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

##addition

In [ ]:
print(a+b)
print(np.add(a,b))

[5 7 9]
[5 7 9]


##multiplication

In [ ]:
print(a*b)
print(np.multiply(a,b))

[ 4 10 18]
[ 4 10 18]


##division

In [ ]:
print(a/b)
print(np.divide(a,b))

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


7.Create a random NumPy array of size (4, 4).

##Mean of each column.


In [ ]:
a=np.random.random((4,4))
b=np.mean(a,axis=0)
print(b)

[0.48058423 0.22953014 0.61977496 0.55919546]


##Maximum value of the entire array

In [ ]:
maximum=np.max(a)
print(maximum)

0.9868466950557844


##Sum of all elements

In [ ]:
soe=np.sum(a)
print(soe)

7.55633911909905


8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2


##add 10

In [ ]:
arr=np.array([1,2,3,4])
add=arr+10
print("after adding 10="add)

##multiply by 2

In [ ]:
mul=add*2
print("after mul by 2="mul)

[22 24 26 28]


9.Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100


In [ ]:
arr=np.random.randint(1,100,(3,4,5))
print(arr)

[[[35 45 82  8 19]
  [ 2 65 57 14 41]
  [47 51 66 37 27]
  [ 5  9 39 36 48]]

 [[62 29 70 35 76]
  [97 59 50 46 58]
  [35 34 37 58 31]
  [83 93 50 59 99]]

 [[60 51 17 26 25]
  [68 74 16 95 82]
  [15 76 68 18 23]
  [ 2 80 94 80 27]]]


####Extract the second "layer" (i.e., the second 2D array) in the first dimension

In [ ]:
second=arr[1]
print(second)

[[62 29 70 35 76]
 [97 59 50 46 58]
 [35 34 37 58 31]
 [83 93 50 59 99]]


###Extract the first two rows and the last three columns from each "layer."

In [ ]:
extract=arr[:,:2,2:5]
print(extract)

[[[82  8 19]
  [57 14 41]]

 [[70 35 76]
  [50 46 58]]

 [[17 26 25]
  [16 95 82]]]


###Replace all elements divisible by 3 with -1

In [ ]:
arr[arr%3==0]=-1
print(arr)

[[[35 -1 82  8 19]
  [ 2 65 -1 14 41]
  [47 -1 -1 37 -1]
  [ 5 -1 -1 -1 -1]]

 [[62 29 70 35 76]
  [97 59 50 46 58]
  [35 34 37 58 31]
  [83 -1 50 59 -1]]

 [[-1 -1 17 26 25]
  [68 74 16 95 82]
  [-1 76 68 -1 23]
  [ 2 80 94 80 -1]]]


10. Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20

In [ ]:
arr=np.random.randint(1,20,(3,3))
print(arr)

[[ 9 16 17]
 [17 15  5]
 [ 4 10  8]]


###Subtract the mean of each row from its respective elements (row-wise normalization)

In [ ]:
mean=np.mean(a)
print(mean)

0.47227119494369063


In [64]:
submean=arr-arr.mean(axis=1,keepdims=True)
print(submean)

[[-5.          2.          3.        ]
 [ 4.66666667  2.66666667 -7.33333333]
 [-3.33333333  2.66666667  0.66666667]]


###Create a new array by squaring all the elements in arr

In [ ]:
squaredarray=np.sqrt(arr)
print(squaredarray)

[[3.         4.         4.12310563]
 [4.12310563 3.87298335 2.23606798]
 [2.         3.16227766 2.82842712]]


###Find the indices of the top 3 maximum values in the entire array

In [67]:
flattenarr=arr.flatten()
values=[]
indices=[]
for i in range(3):
  max_value=flattenarr.max()
  max_index=flattenarr.argmax()
  values.append(max_value)
  indices.append(max_index)
  flattenarr[max_index]=-1
print("indices of top 3 max values=",indices)

indices of top 3 max values= [2, 3, 1]
